
development: 
  adapter: postgresql
  database: my_blog_app_development
  encoding: unicode
  host: localhost
  password: admin
  pool: 5
  username: postgres
production: 
  url: postgres://postgres:admin@localhost/my_blog_app_production
test: 
  adapter: postgresql
  database: my_blog_app_test
  url: postgres://postgres:admin@localhost/my_blog_app_test
  encoding: unicode
  password: admin
  pool: 5
